
plugins {
    id "java-library"
}

repositories {
    mavenCentral()
    gradlePluginPortal()
}

dependencies {

    implementation("org.apache.commons:commons-lang3:3.19.0")

    implementation("org.slf4j:jcl-over-slf4j:1.7.20")
    implementation("ch.qos.logback:logback-classic:1.1.7")
    implementation("net.logstash.logback:logstash-logback-encoder:6.3")
}
